name: 'srctag'
description: 'Diff source files with real-world stories.'
branding:
  color: 'blue'
  icon: 'tag'

inputs:
  tags:
    description: 'Tags for classify'
    required: true
    default: './srctag.txt'
  before_sha:
    description: 'before sha'
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  after_sha:
    description: 'after sha'
    required: true
    default: ${{ github.event.pull_request.head.sha }}
  repo_token:
    description: "A GitHub token for API access. Defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: false
  issue_number:
    description: "issue number"
    default: "${{ github.event.number }}"
    required: false
  n_result:
    description: "how many tags can be tagged on a single file"
    default: "3"
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/williamfzc/srctag-action:latest'
  args:
    - ${{ inputs.tags }}
    - ${{ inputs.before_sha }}
    - ${{ inputs.after_sha }}
    - ${{ inputs.repo_token }}
    - ${{ inputs.issue_number }}
    - ${{ inputs.n_result }}
