on:
  push:
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Smoke Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test Action
        uses: ./
