on:
  push:
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  pull-requests: write

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Smoke Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test Action
        uses: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: srctag-dot
          path: ${{ github.workspace }}/srctag.dot
